// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwwopxqwcfyeogketibt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3d29weHF3Y2Z5ZW9na2V0aWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODgwMjksImV4cCI6MjA2MTg2NDAyOX0.QJlis2JT4sNMVuYevx9izuj3AlpsfjlV5ndyzKJRPGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);